### PR TITLE
Cybercamp2021-changes

### PR DESCRIPTION
**Pull request by CalCraven**
This PR will update mosdef-tutorials for the 2021 summer cybercamp for incoming students. Changes include but are not limited to:
- [x] Fix overview.ipynb to utilize new polymer mBuild class
- [x] Fix mbuild-overiview.ipynb which also uses new polymer mbuild class
- [x] Add support for pytests performed on xml files in Foyer-overview.ipynb
- [ ] etc

### CODE REVIEW

**Comment by daico007** [comment]
Can you clear the output of all the notebooks?

**Comment by CalCraven** [comment]
Those should be cleared now, forgot to hit save on the notebook file before shutting down.

**Comment by bc118** [comment]
I reinstalled everything, but the "overview.ipynb" it is not working once I get here:
from utils import Alkane
octane = Alkane(chain_length=8)
octane.visualize()

It does not like the "from utils import Alkane" and is then giving the error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-530879afd2b0> in <module>
      1 from utils import Alkane
----> 2 octane = Alkane(chain_length=8)
      3 octane.visualize()

~/Programs/GIT_repositories/mosdef_tutorials/mosdef_tutorials/utils/alkane.py in __init__(self, chain_length)
     21 
     22         # Create a polymer of CH2 units
---> 23         chain = mb.recipes.Polymer(CH2(), n=chain_length, port_labels=('up', 'down'))
     24         self.add(chain, 'chain')
     25 

TypeError: __init__() got an unexpected keyword argument 'n'

**Comment by bc118** [comment]
_**Fo the "mbuild-overview" file in the "Loading in Compounds" sections the following error :**_

polymer = recipes.Polymer(monomers=CH2(), n=10)
locations = mb.pattern.Grid2DPattern(n=10, m=10)
functionalized_surface = recipes.Monolayer(AmorphousSilicaSurface(),
                                           polymer, backfill=H(), pattern=locations,
                                           tile_x=2, tile_y=1,)
                                           
**_ERROR:_**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-7f5d69b4b8a3> in <module>
     18                          separation=0.07), label='down')
     19 
---> 20 polymer = recipes.Polymer(monomers=CH2(), n=10)
     21 locations = mb.pattern.Grid2DPattern(n=10, m=10)
     22 functionalized_surface = recipes.Monolayer(AmorphousSilicaSurface(),

TypeError: __init__() got an unexpected keyword argument 'n'

**Comment by bc118** [comment]
I did not read the lines for the following files "mbuild-overview.ipynb", "overview.ipynb", and "foyer-overview.ipynb".  I ran the code and it seemed to run OK less the comment above.

**Comment by CalCraven** [comment]
@bc118 Did that end up working for you? 

 """
polymer = recipes.Polymer(monomers=CH2(), n=10)
locations = mb.pattern.Grid2DPattern(n=10, m=10)
functionalized_surface = recipes.Monolayer(AmorphousSilicaSurface(),
polymer, backfill=H(), pattern=locations,
tile_x=2, tile_y=1,)
"""

This code that you referenced I think is line 531-535 in `mbuild-overview.ipynb`, but it looks like your version is slightly different. Seems like the lines should work okay. Here is the relevant code:

"""
> python
> "polymer = recipes.Polymer(monomers=[CH2()])\n",    
> "polymer.build(n=10)\n",    
> "polymer.remove(polymer[-1])\n",    
> "polymer.add(polymer.all_ports()[0], 'down', containment=False)\n",    
> "locations = mb.pattern.Grid2DPattern(n=10, m=10)\n",
"""

**Comment by bc118** [comment]
This part was still not working.  The other part that I got working was removed from the comments

**Comment by CalCraven** [comment]
I just installed a fresh clone and it ran all the way through. Can you show me exactly where that those lines were? Maybe I'm looking in the wrong place. The code looks different between what you posted and what's on the branch, if I'm looking in the right spot.

**Comment by CalCraven** [comment]
More specifically, I don't have `polymer = recipes.Polymer(monomers=CH2(), n=10)` anywhere in my notebook.

**Comment by bc118** [comment]
OK.  I redownloaded that part and it is like you said above and seems to work now.  So I think we are good.  Maybe I had opened the wrong one. IDK

**Comment by CalCraven** [comment]
No worries, glad that it's running properly! @justinGilmer do you want to merge this before we get started today?

**Pull request merged**
